# Generated by Django 6.0.7 on 2026-07-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="movie",
            name="movies_movi_categor_3d8279_idx",
        ),
        migrations.RenameIndex(
            model_name="movie",
            new_name="movies_movi_is_tren_c5976e_idx",
            old_name="movies_movi_is_tren_2aaa84_idx",
        ),
        migrations.RenameIndex(
            model_name="movie",
            new_name="movies_movi_is_new__66dce9_idx",
            old_name="movies_movi_is_new__4458de_idx",
        ),
        migrations.RenameIndex(
            model_name="movie",
            new_name="movies_movi_is_feat_77d1d8_idx",
            old_name="movies_movi_is_feat_b67c49_idx",
        ),
        migrations.RenameIndex(
            model_name="movie",
            new_name="movies_movi_created_619207_idx",
            old_name="movies_movi_created_36c764_idx",
        ),
        migrations.RenameIndex(
            model_name="movie",
            new_name="movies_movi_views_887f5d_idx",
            old_name="movies_movi_views_8e3043_idx",
        ),
        migrations.RenameIndex(
            model_name="movie",
            new_name="movies_movi_rating_8fd49a_idx",
            old_name="movies_movi_rating_872ab8_idx",
        ),
        migrations.RenameIndex(
            model_name="movie",
            new_name="movies_movi_year_82d175_idx",
            old_name="movies_movi_year_e90d32_idx",
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["category"], name="movies_movi_categor_a7fa32_idx"
            ),
        ),
    ]
