# Generated by Django 6.0.5 on 2026-09-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.CharField(max_length=255)),
                ("movie_title", models.CharField(blank=True, max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("download", "Download"),
                            ("trailer_watch", "Trailer watch"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
